### ISSUE TITLE
Device Address API responded with a status code of : 204

### ISSUE THREAD

**Issue by Kee43** [alexa/skill-sample-node-device-address-api#9]
Hi,

I'm struggling to get a response from the devices api (eu endpoint):
https://api.eu.amazonalexa.com/v1/devices/[deviceID]/settings/address

It's returning with a response of 204 and it's not complaining about the auth token.

I have a physical device with me, is there a way of getting the deviceID from that and using it to test with? I understand you can't test the address API with the Alexa simulator which makes debugging a bit difficult.

Thanks.

**Comment by franklin-lobb** [comment]
Hi @Kee43 - this doesn't sound like an issue with this sample code.  (If that's not correct, please reopen/clarify.)

The [Alexa Developer Forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html) would be the best source for general troubleshooting help. If you're still having issues, please post there.
